### ISSUE TITLE
[질문] 마크다운 렌더링이 좀 다른가요? 

### ISSUE THREAD

**Issue by ikaruce** [devlog/devlog.github.io#8]
마크다운이 정상적으로 보이는데, 블로그 페이지에서는 제대로 안보이는 문제가 있는데, 혹시 쓰면 안되는 문법이 있다거나 그런건가요?

**Comment by yms9654** [comment]
Jekyll이 사용하는 마크다운 엔진이 좀 다른것 같네요.
검색해보니 http://www.dpetzel.info/tips/jekyll/2015/01/04/jekyll-with-fenced-code-blocks.html 이런 글이 있어서
_config 수정해서 엔진을 redcarpet 으로 변경하고 코드블럭 앞에 newline을 추가하니 좀 제대로 보이는것 같습니다.^^

**Comment by ikaruce** [comment]
:+1:  그렇군요!!
